RVABIKESHOP.WEB/Models/ErrorViewModel.cs
namespace ESCOOTERRENT.WEB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RVABIKESHOP.WEB/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ESCOOTERRENT.Services;

namespace ESCOOTERRENT.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly IScooterService scooterService;
        private readonly IStoreService storeService;
        private readonly ITypeService typeService;

        public HomeController(IScooterService scooterService, IStoreService storeService, ITypeService typeService)
        {
            this.scooterService = scooterService;
            this.storeService = storeService;
            this.typeService = typeService;
        }

        public IActionResult Index()
        {
            ViewData["StoresList"] = storeService.ReadAll();
            ViewData["TypesList"] = typeService.ReadAll();
            return View(scooterService.ReadAll());
        }

        public IActionResult Rent(int id)
        {
            return View(scooterService.ReadOne(id));
        }        
    }
}

RVABIKESHOP.WEB/Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using ESCOOTERRENT.Services;

namespace ESCOOTERRENT.WEB.Controllers
{
    public class StoreController : Controller
    {
        private readonly IStoreService storeService;
  
        public StoreController(IStoreService storeService)
        {
            this.storeService = storeService;
        }
        public IActionResult Stores()
        {
            return View(storeService.ReadAll());
        }     
    }
}

RVABIKESHOP.WEB/Views/Home/Delete.cshtml
<div class="container mt-5 mb-5">
	<h1>Scooter was deleted!</h1>
</div>

RVABIKESHOP.WEB/Views/Home/Index.cshtml
@using ESCOOTERRENT.Data
@using ESCOOTERRENT.Models

@{
    ViewData["Title"] = "Scooters";
}
@model List<ScooterModel>

@{
    var stores = (List<StoreModel>)ViewData["StoresList"];
    var types = (List<TypeModel>)ViewData["TypesList"];
}
<style>
    .cardText {
    text-align:start;
    }
</style>

<link rel="stylesheet" href="~/css/Dropdown.css">
<link rel="stylesheet" href="~/css/Button.css">
<link rel="stylesheet" href="~/css/Card.css">

<div style="height: 100%"> 
    <div class="row">
         @foreach (ScooterModel scooter in @Model)
          {
            <div class="column">
                <div class="card">

                  <h3>@scooter.Name</h3>
                    @{
                        var type = types.Find(x => x.Id == @scooter.TypeId);
                        switch(type.Id)
                        {
                            case 1:
                                 <img src="~/img/scooter_1.jpg">
                            break;
                            case 2:
                                 <img src="~/img/scooter_2.jpg">
                            break;
                            case 3:
                                 <img src="~/img/scooter_3.jpg">
                            break;
                            case 4:
                                 <img src="~/img/scooter_4.jpg">
                            break;
                            default:
                                 <img src="~/img/scooter_3.jpg">
                            break;
                        }                                 
                    }                                                    
                   
                  <p class="cardText">Bycicle type: @type.Name</p>
                  <p class="cardText">Price: @scooter.Price dinars</p>
                  <p class="cardText">Description: @scooter.Description</p>
                  @if (scooter.Available) 
                  {                 
                    <p style="color:green;">Status: In stock</p>                  
                  }
                  else
                  {
                    <p style="color:red;">Status: Not in stock</p>
                  }
                  <a style="color:blue; text-align:center;" asp-action="Rent" asp-controller="Home" asp-route-id="@scooter.Id">Rent</a>
                </div>
            </div>
          }    
    </div>
</div>

RVABIKESHOP.WEB/Views/Home/Rent.cshtml
@using ESCOOTERRENT.Data
@using ESCOOTERRENT.Models

@model ScooterModel

<div class="container mt-5 mb-5">
   <div class="row">
      <div class="col-12">
         <div class="card z-index-0 fadeIn3 fadeInBottom">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
               <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                  <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">Check scooter information</h4>
               </div>
            </div>
            <div class="card-body">               
                   <input type="hidden" asp-for="Id"/>
                  <div class="input-group input-group-outline my-3">
                     <label asp-for="Name"></label>
                     <input asp-for="Name" class="form-control w-100" disabled>
                     <span asp-validation-for="Name" class="text-danger"></span>
                  </div>           
                   <div class="input-group input-group-outline my-3">                         
                     <label asp-for="Price"></label>
                     <input asp-for="Price" class="form-control w-100" disabled>
                     <span asp-validation-for="Price" class="text-danger"></span>
                  </div>
                  <div class="input-group input-group-outline my-3">                         
                     <label asp-for="Description"></label>
                     <input asp-for="Description" class="form-control w-100" disabled>
                     <span asp-validation-for="Description" class="text-danger"></span>
                  </div>
                   <div class="form-check form-switch d-flex align-items-center">
                       <input class="form-check-input" type="checkbox" id="rememberMe" asp-for="Available" disabled>
                       <label class="form-check-label mb-0 ms-2" asp-for="Available"></label>
                   </div>                   
                  <div class="text-center">
                     <button type="submit" class="btn bg-gradient-primary w-100">Rent scooter</button>                    
                  </div>          
            </div>
         </div>
      </div>
   </div>
</div>

RVABIKESHOP.WEB/Views/Shared/Scripts.cshtml
<!--   Core JS Files   -->
  <script src="~/js/core/popper.min.js"></script>
  <script src="~/js/core/bootstrap.min.js"></script>
  <script src="~/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="~/js/plugins/smooth-scrollbar.min.js"></script>
  <script src="~/js/plugins/chartjs.min.js"></script>
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script src="~/js/plugins/github_buttons.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="~/js/material-dashboard.min.js?v=3.0.2"></script>

RVABIKESHOP.WEB/Views/Shared/Sidenavbar.cshtml
 <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" asp-action="Index">
        <img src="~/img/scooter_logo.jpg" class="navbar-brand-img h-100" alt="main_logo">
        <span class="ms-1 font-weight-bold text-white">E-Scooters Rent</span>
      </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto  max-height-vh-100" id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white" asp-action="Index" asp-controller="Home" asp-area="">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">dashboard</i>
            </div>
            <span class="nav-link-text ms-1">Scooters</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" asp-action="Stores" asp-controller="Store" asp-area="">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">table_view</i>
            </div>
            <span class="nav-link-text ms-1">Stores</span>
          </a>
        </li>
      </ul>
    </div>
  </aside>

RVABIKESHOP.WEB/Views/Shared/Styles.cshtml
  <link rel="apple-touch-icon" sizes="76x76" href="~/img/apple-icon.png">
  <link rel="icon" type="image/png" href="~/img/favicon.png">
  <!-- Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="~/css/Roboto.css" />
  <!-- Nucleo Icons -->
  <link href="~/css/nucleo-icons.css" rel="stylesheet" />
  <link href="~/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="~/js/plugins/font_aswseome_external_link.js"></script>
  <!-- Material Icons -->
  <link href="~/css/Material.css" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="~/css/material-dashboard.css?v=3.0.2" rel="stylesheet" />

RVABIKESHOP.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>
        @ViewData["Title"] - ESCOOTERRENT.Web
      </title>
      <partial name="Styles" />
      @await RenderSectionAsync("Styles", required: false)
  </head>

    <body class="g-sidenav-show  bg-gray-200">
      <partial name="Sidenavbar" />
      <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
        <div class="container-fluid py-4">
          @RenderBody()
        </div>
      </main>
    </body>
    <partial name="Scripts" />
    @await RenderSectionAsync("Scripts", required: false)
</html>

RVABIKESHOP.WEB/Views/Store/Stores.cshtml
@using ESCOOTERRENT.Data
@using ESCOOTERRENT.Models

@model List<StoreModel>

<link rel="stylesheet" href="~/css/Card.css">

<div style=" height: 100%">
    <div class="row">
         @foreach (StoreModel store in @Model)
          {
            <div class="column">
                <div class="card">
                  <img src="~/img/store.jpg" >
                  <h3>@store.Name</h3>                 
                  <p>@store.Location</p>  
                  <p>Working hours: @store.WorkingHours</p> 
                </div>
            </div>
          }    
    </div>
</div>